<template>
  <v-tabs vertical v-model="tab">
    <v-tab>
      Introduction
    </v-tab>
    <v-tab>
      Dataset
    </v-tab>
    <v-tab>
      Map
    </v-tab>
    <v-tab>
      Crossfilters
    </v-tab>
    <v-tab>
      Downloading
    </v-tab>

    <!-- Introduction -->
    <v-tab-item eager transition="none" reverse-transition="none">
      <v-card flat>
        <v-card-text class="black--text body-1 pt-0">
          <div class="headline mb-4 mt-4">Welcome to the User's Guide</div>
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The <strong>RESTORE Data Visualization Tool</strong> was created by the U.S. Geological Survey Lower Mississippi-Gulf Water Science Center
                to provide access to various streamflow-related datasets generated by USGS researchers as part of the
                <a href="https://www.usgs.gov/centers/lmg-water/science/streamflow-alteration-assessments-support-bay-and-estuary-restoration-gulf?qt-science_center_objects=0#qt-science_center_objects" target="_blank">RESTORE project</a>.
              </p>
              <p>
                Using the interactive map and crossfilters, users can explore these datasets and identify patterns and trends related to streamflow
                conditions among the basins draining to the Gulf of Mexico.
              </p>
              <p>
                This guide is divided into the following sections:
              </p>
              <ul>
                <li>
                  <a @click="tab = 1" class="font-weight-black text-uppercase">Dataset</a>: How to load a dataset
                </li>
                <li>
                  <a @click="tab = 2" class="font-weight-black text-uppercase">Map</a>: How to view different variables on the map and get more details about each streamflow gage/12-digit hydrologic unit code (HUC12) basin
                </li>
                <li>
                  <a @click="tab = 3" class="font-weight-black text-uppercase">Crossfilters</a>: How to filter the datasets and identify spatial patterns and relationships between variables
                </li>
                <li>
                  <a @click="tab = 4" class="font-weight-black text-uppercase">Downloading</a>: How to download data for external analyses
                </li>
              </ul>
            </v-col>
            <v-col lg="7" cols="12">
              <video controls :width="$vuetify.breakpoint.xl ? 750 : $vuetify.breakpoint.lg ? 650 : 600">
                <source src="video/showreel.mp4" type="video/mp4">
                Sorry, your browser doesn't support embedded videos.
              </video>
              <div class="caption">Introduction video</div>
            </v-col>
          </v-row>

          <v-divider class="mt-4"></v-divider>

          <v-card-actions class="pt-8 px-0">
            <v-btn disabled color="primary" class="" @click="prevTab"><v-icon>mdi-chevron-left</v-icon>Previous</v-btn>
            <v-spacer></v-spacer>
            <v-btn color="primary" class="" @click="nextTab">Next <v-icon>mdi-chevron-right</v-icon></v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-tab-item>

    <!-- Dataset -->
    <v-tab-item eager transition="none" reverse-transition="none">
      <v-card flat>
        <v-card-text class="black--text body-1 pt-0">
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The <strong>Dataset</strong> tab shows the name of the current dataset and may include one or more of the following inputs:
              </p>
              <ul class="mb-4">
                <li>
                  For datasets vary by decade, the <strong>Decade Slider</strong> allows you to move through time. The
                  selected decade will affect both the values shown on the map, as well as the values represented in the
                  crossfilter histograms. Note that some variables do not vary by decade (e.g., Basin Area).
                </li>
                <li>
                  For datasets that include trend analysis results, a checkbox allows you to include <strong>only significant (p &lt; 0.05) trend
                  results</strong>. This option will affect both the variable shown on the map, as well as the crossfilters whenever a trend analysis
                  variable is selected. Note that it will not affect any of the other variables.
                </li>
              </ul>
              <p>
                To load a different dataset, click the <strong>Dataset Browser</strong> button at the bottom of the Dataset tab.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/dataset.png"
                alt="Dataset Loaded"
                style="border:1px solid darkgray;border-radius:10px"></v-img>
            </v-col>
          </v-row>

          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The <strong>Dataset Browser</strong> lists the available datasets that can be loaded into the application.
              </p>
              <p>
                Select a dataset from the list, and then click the <strong>Load Dataset</strong> button to load it into the application.
              </p>
              <p>
                There are two groups of datasets:
              </p>
              <ol class="mb-4">
                <li>Streamflow Gages</li>
                <li>12-digit Hydrologic Unit Code (HUC12) Basins</li>
              </ol>
              <p>
                Datasets in the first group provide data at USGS streamflow gage locations. Datasets in the second group provide data
                for all HUC12 basins draining to the Gulf of Mexico (including both gaged and ungaged basins).
              </p>
              <p>
                The <strong>Primary Dataset</strong> for each group combines key variables from each of the other datasets.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/dataset-browser.png"
                alt="Dataset Browser Screenshot"
                style="border:1px solid darkgray;border-radius:10px"></v-img>
            </v-col>
          </v-row>

          <v-divider></v-divider>

          <v-card-actions class="pt-8 px-0">
            <v-btn color="primary" class="" @click="prevTab"><v-icon>mdi-chevron-left</v-icon>Previous</v-btn>
            <v-spacer></v-spacer>
            <v-btn color="primary" class="" @click="nextTab">Next <v-icon>mdi-chevron-right</v-icon></v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-tab-item>

    <!-- Map -->
    <v-tab-item eager transition="none" reverse-transition="none">
      <v-card flat>
        <v-card-text class="black--text body-1 pt-0">
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The <strong>Map</strong> shows the values of a single variable at all streamflow gages or HUC12 basins in the region
                (depending on which dataset is loaded). When a HUC12 dataset is loaded, each basin is represented by the location of its pour point,
                which is where all water from the contributing areas both within the basin and from any upstream basins drains.
              </p>
              <p>
                Use the drop down menu on the <strong>Variable</strong> tab in the middle box to select which variable is shown on the map.
              </p>
              <p>
                The bottom box contains a legend showing the values corresponding to the range of colors.
                To change the color scheme, open the <strong>Legend Settings</strong> by clicking on the gear icon.
              </p>
              <p>
                The <strong>Map Controls</strong> are located in the upper-right corner and let you zoom in and out, and change the basemap.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/map.png"
                alt="Map Variable Tab"
                style="border:1px solid darkgray;border-radius:10px"></v-img>
            </v-col>
          </v-row>
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                Lastly, you can click on a point on the map to select a streamflow gage or HUC12 basin, which will open the
                <strong>Details Sidebar</strong> that contains a data summary and series of charts for the selected streamflow gage/HUC12 basin.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/map-details.png"
                alt="Map Details Screenshot"
                style="border:1px solid darkgray;border-radius:10px"></v-img>
            </v-col>
          </v-row>

          <v-divider class="mt-4"></v-divider>

          <v-card-actions class="pt-8 px-0">
            <v-btn color="primary" class="" @click="prevTab"><v-icon>mdi-chevron-left</v-icon>Previous</v-btn>
            <v-spacer></v-spacer>
            <v-btn color="primary" class="" @click="nextTab">Next <v-icon>mdi-chevron-right</v-icon></v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-tab-item>

    <!-- Crossfilters -->
    <v-tab-item eager transition="none" reverse-transition="none">
      <v-card flat>
        <v-card-text class="black--text body-1 pt-0">
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The <strong>Crossfilters</strong> are interactive histograms used to dynamically filter the dataset and see the distribution
                of values for one or more variables.
              </p>
              <p>
                Select the <strong>Crossfilters</strong> tab from the middle box, then use the drop down menu to select one or more
                variables.
              </p>
              <p>
                For each selected variable, a crossfilter (interactive histogram) is created showing the number of streamflow gages or HUC12 basins
                for each bin of values.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/crossfilters.png"
                alt="Crossfilters Screenshot"
                style="border:1px solid darkgray;border-radius:10px;"></v-img>
            </v-col>
          </v-row>
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                Click and drag on the crossfilter to set a <strong>filter range</strong>, which will instantaneously filter the dataset (i.e. set of
                streamflow gages or HUC12 basins).
                When a filter range is set, only the streamflow gages or HUC12 basins with values within that range are shown on the map. Filtering on
                one crossfilter will also cause the histograms in the other crossfilters to update, since these other histograms only include the
                streamflow gages/HUC12 basins that meet that first filter.
              </p>
              <p>
                The crossfilters can be used to not only identify streamflow gages/HUC12 basins that meet certain conditions. But by interactively
                sliding the filter ranges,
                you can see how one variable is correlated to another.
              </p>
              <p>
                As an example, the animation to the right has crossfilters for Basin Area, Base Flow Index, and Mean Streamflow.
                As the filter range on Basin Area (top) is moved from left to right, the histogram of the Mean Streamflow (bottom) also
                shifts from left to right.
                This indicates a positive correlation between the two variables with streamflow gages having larger basin areas also having
                higher mean streamflow.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <video controls :width="$vuetify.breakpoint.xl ? 780 : $vuetify.breakpoint.lg ? 650 : 800">
                <source src="video/crossfilters.mp4" type="video/mp4">
                Sorry, your browser doesn't support embedded videos.
              </video>
              <div class="caption">Video demonstrating crossfilter interaction</div>
            </v-col>
          </v-row>

          <v-divider class="mt-4"></v-divider>

          <v-card-actions class="pt-8 px-0">
            <v-btn color="primary" class="" @click="prevTab"><v-icon>mdi-chevron-left</v-icon>Previous</v-btn>
            <v-spacer></v-spacer>
            <v-btn color="primary" class="" @click="nextTab">Next <v-icon>mdi-chevron-right</v-icon></v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-tab-item>

    <!-- Download -->
    <v-tab-item eager transition="none" reverse-transition="none">
      <v-card flat>
        <v-card-text class="black--text body-1 pt-0">
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                To download data, click the <strong>Download</strong> button at the bottom of the <strong>Dataset</strong> tab.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/download-button.png"
                alt="Download Button Screenshot"
                max-width="400"
                style="border:1px solid darkgray;border-radius:10px"></v-img>
            </v-col>
          </v-row>
          <v-row>
            <v-col lg="5" cols="12">
              <p>
                The Download screen provides two options for downloading the current dataset:
              </p>

              <ol class="mb-4">
                <li>
                  <strong>Complete Dataset</strong> will include data for all decades (if applicable) and
                  all streamflow gages or HUC12 basins regardless of any crossfilters that may be set.
                </li>
                <li>
                  <strong>Filtered Dataset</strong> will only include data for the current selected decade and the streamflow
                  gages/HUC12 basins that meet the current crossfilter criteria.
                </li>
              </ol>

              <p>
                Both options will generate a comma-separated value (CSV) file that can be opened in Microsoft Excel or any other
                data analysis software. This file will include multiple lines of metadata such as the name of the dataset, citations,
                and descriptions of each column.
              </p>
            </v-col>
            <v-col lg="7" cols="12">
              <v-img
                src="img/user-guide/download.png"
                alt="Download Screenshot"
                style="border:1px solid darkgray;border-radius:10px;"></v-img>
            </v-col>
          </v-row>

          <v-divider class="mt-4"></v-divider>

          <v-card-actions class="pt-8 px-0">
            <v-btn color="primary" class="" @click="prevTab"><v-icon>mdi-chevron-left</v-icon>Previous</v-btn>
            <v-spacer></v-spacer>
            <v-btn disabled color="primary" class="" @click="nextTab">Next <v-icon>mdi-chevron-right</v-icon></v-btn>
          </v-card-actions>
        </v-card-text>
      </v-card>
    </v-tab-item>
  </v-tabs>
</template>

<script>
export default {
  name: 'UserGuide',
  data () {
    return {
      tab: 0
    }
  },
  methods: {
    scroll () {
      this.$vuetify.goTo(0, { container: this.$el.parentElement, duration: 0 })
    },
    nextTab () {
      this.scroll()
      this.$nextTick(() => {
        this.tab += 1
      })
    },
    prevTab () {
      this.scroll()
      this.$nextTick(() => {
        this.tab -= 1
      })
    }
  }
}
</script>
