<template>
  <v-tabs vertical v-model="tab">
    <v-tab>
      Introduction
    </v-tab>
    <v-tab>
      Dataset Browser
    </v-tab>
    <v-tab>
      Map
    </v-tab>
    <v-tab>
      Crossfilters
    </v-tab>
    <v-tab>
      Downloading
    </v-tab>

    <v-tab-item>
      <v-card flat>
        <v-card-text class="black--text body-1">
          <!-- WELCOME -->
          <p class="headline">
            Welcome to the User's Guide
          </p>
          <p>
            The <strong>RESTORE Data Visualization Tool</strong> was created by the U.S. Geological Survey Lower Mississippi-Gulf Water Science Center
            to provide access to various streamflow-related datasets generated by USGS researchers as part of the
            <a href="https://www.usgs.gov/centers/lmg-water/science/streamflow-alteration-assessments-support-bay-and-estuary-restoration-gulf?qt-science_center_objects=0#qt-science_center_objects" target="_blank">RESTORE project</a>.
          </p>
          <p>
            Using the interactive map and crossfilters, users can explore these datasets and identify patterns and trends related to streamflow
            conditions among the basins draining to the Gulf of Mexico.
          </p>
          <p>
            This guide is divided into the following sections:
          </p>
          <ul>
            <li>
              <a @click="tab = 1" class="font-weight-black text-uppercase">Dataset Browser</a>: How to load a dataset
            </li>
            <li>
              <a @click="tab = 2" class="font-weight-black text-uppercase">Map</a>: How to view different variables on the map and get more details about each streamflow gage/12-digit hydrologic unit code (HUC12) basin
            </li>
            <li>
              <a @click="tab = 3" class="font-weight-black text-uppercase">Crossfilters</a>: How to filter the datasets and identify spatial patterns and relationships between variables
            </li>
            <li>
              <a @click="tab = 4" class="font-weight-black text-uppercase">Downloading</a>: How to download data for external analyses
            </li>
          </ul>
        </v-card-text>
      </v-card>
    </v-tab-item>
    <v-tab-item>
      <v-card flat>
        <v-card-text class="black--text body-1">
          <!-- DATASET -->
          <v-img
            src="../assets/img/user-guide/dataset-browser.png"
            alt="Dataset Browser Screenshot"
            width="600"
            class="ml-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>
          <p>
            The <strong>Dataset Browser</strong> lists the available datasets that can be loaded into the application.
          </p>
          <!-- <v-img
            src="../assets/img/user-guide/dataset-browser-button.png"
            alt="Dataset Browser Button Screenshot"
            width="300"
            class="ml-2 my-4"
            style="border:1px solid darkgray;border-radius:10px"></v-img> -->
          <p>
            Select a dataset from the list, and then click the <code>Load Dataset</code> button to load it into the application.
          </p>
          <p>
            There are two groups of datasets:
          </p>
          <ol class="mb-4">
            <li>Streamflow Gages</li>
            <li>12-digit Hydrologic Unit Code (HUC12) Basins</li>
          </ol>
          <p>
            Datasets in the first group provide data at USGS streamflow gage locations. Datasets in the second group provide data
            for all HUC12 basins draining to the Gulf of Mexico (including both gaged and ungaged basins).
          </p>
          <p>
            The <strong>Primary Dataset</strong> for each group combines key variables from each of the other datasets.
          </p>
        </v-card-text>
      </v-card>
    </v-tab-item>
    <v-tab-item>
      <v-card flat>
        <v-card-text class="black--text body-1">
          <!-- MAP -->
          <v-img
            src="../assets/img/user-guide/map.png"
            alt="Map Screenshot"
            width="600"
            class="ml-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>
          <v-img
            src="../assets/img/user-guide/map-details.png"
            alt="Map Details Screenshot"
            width="600"
            class="ml-4 mt-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>
          <p>
            The <strong>Map</strong> shows the values of a single variable at all streamflow gages or HUC12 basins in the region
            (depending on which dataset is loaded). When a HUC12 dataset is loaded, each basin is represented by the location of its pour point,
            which is where all water from the contributing areas both within the basin and from any upstream basins drains.
          </p>
          <p>
            For datasets and variables that vary by decade, use the <strong>Decade Slider</strong> in the top box to move through time.
          </p>
          <p>
            Use the drop down menu on the <strong>Variable</strong> tab in the middle box to select which variable is shown on the map.
          </p>
          <p>
            The bottom box contains a legend showing the values corresponding to the range of colors.
            To change the color scheme, open the <strong>Legend Settings</strong> by clicking on the gear icon.
          </p>
          <p>
            The <strong>Map Controls</strong> are located in the upper-right corner and let you zoom in and out, and change the basemap.
          </p>
          <p>
            Lastly, you can click on a point on the map to select a streamflow gage or HUC12 basin, which will open the
            <strong>Details Sidebar</strong> that contains a data summary and series of charts for the selected streamflow gage/HUC12 basin.
          </p>
        </v-card-text>
      </v-card>
    </v-tab-item>
    <v-tab-item>
      <v-card flat>
        <v-card-text class="black--text body-1">
          <!-- CROSSFILTERS -->
          <v-img
            src="../assets/img/user-guide/crossfilters.png"
            alt="Crossfilters Screenshot"
            width="600"
            class="ml-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>
          <v-img
            src="../assets/img/user-guide/crossfilters-animate.gif"
            alt="Map Screenshot"
            width="600"
            class="ml-4 mt-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>

          <p>
            The <strong>Crossfilters</strong> are interactive histograms used to dynamically filter the dataset and see the distribution
            of values for one or more variables.
          </p>
          <p>
            Select the <strong>Crossfilters</strong> tab from the middle box, then use the drop down menu to select one or more
            variables.
          </p>
          <p>
            For each selected variable, a crossfilter (interactive histogram) is created showing the number of streamflow gages or HUC12 basins for each bin of values.
          </p>
          <p>
            Click and drag on the crossfilter to set a <strong>filter range</strong>, which will instantaneously filter the dataset (i.e. set of streamflow gages or HUC12 basins).
            When a filter range is set, only the streamflow gages or HUC12 basins with values within that range are shown on the map. Filtering on
            one crossfilter will also cause the histograms in the other crossfilters to update, since these other histograms only include the
            streamflow gages/HUC12 basins that meet that first filter.
          </p>
          <p>
            The crossfilters can be used to not only identify streamflow gages/HUC12 basins that meet certain conditions. But by interactively sliding the filter ranges,
            you can see how one variable is correlated to another.
          </p>
          <p>
            As an example, the animation to the right has crossfilters for Basin Area and Mean Streamflow. As the filter range on Basin Area (top)
            is moved from left to right, the histogram of the Mean Streamflow (bottom) also shifts from left to right.
            This indicates a positive correlation between the two variables with streamflow gages having larger basin areas also having higher mean streamflow.
          </p>
        </v-card-text>
      </v-card>
    </v-tab-item>
    <v-tab-item>
      <v-card flat>
        <v-card-text class="black--text body-1">
          <!-- DOWNLOAD -->
          <v-img
            src="../assets/img/user-guide/download.png"
            alt="Download Screenshot"
            width="600"
            class="ml-4"
            style="border:1px solid darkgray;border-radius:10px;float:right"></v-img>

          <p>
            To <strong>Download</strong> data from the application, click the Download button in the top box.
          </p>

          <v-img
            src="../assets/img/user-guide/download-button.png"
            alt="Download Button Screenshot"
            width="300"
            class="ml-4 my-4"
            style="border:1px solid darkgray;border-radius:10px"></v-img>

          <p>
            Then click the <code>Complete Dataset</code> button to download all data for the current dataset.
          </p>

          <p>
            Or click the <code>Filtered Dataset</code> button to only download data for streamflow gages/HUC12 basins that meet the current crossfilter criteria.
          </p>

        </v-card-text>
      </v-card>
    </v-tab-item>
  </v-tabs>
</template>

<script>
export default {
  name: 'UserGuide',
  data () {
    return {
      tab: 0
    }
  }
}
</script>
